name: CI/CD deploy release

on:
  push:
    branches: [ "deploy-release" ]
  pull_request:
    branches: [ "deploy-release" ]

jobs:
  ci_cd_deploy_release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build setup
        run: npm run build --configuration production

      - name: Copy files to docs
        run: |
          mkdir -p docs
          cp dist/mycv/browser/*.* docs/

      - name: Git commit and push docs
        env:
          CI_COMMIT_MESSAGE: deploy update from workflow
          CI_COMMIT_AUTHOR: l apajara
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "lapajara@example.com"
          git add docs
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

